(* This file has been auto-generated by the SPL compiler *)
type t = [
  |`Recover
  |`RestartElection
  |`StartElection
  |`Startup
  |`StepDown_from_Candidate
  |`StepDown_from_Leader
  |`WinElection
]

let string_of_statecall (x:t) = match x with
  |`Recover -> "Recover"
  |`RestartElection -> "RestartElection"
  |`StartElection -> "StartElection"
  |`Startup -> "Startup"
  |`StepDown_from_Candidate -> "StepDown_from_Candidate"
  |`StepDown_from_Leader -> "StepDown_from_Leader"
  |`WinElection -> "WinElection"

