(* This file has been auto-generated by the SPL compiler *)
type t = [
  |`Recover
  |`RestartElecton
  |`StartElecton
  |`Startup
  |`StepDown_from_Candidate
  |`StepDown_from_Leader
  |`WinElecton
]

let string_of_statecall (x:t) = match x with
  |`Recover -> "Recover"
  |`RestartElecton -> "RestartElecton"
  |`StartElecton -> "StartElecton"
  |`Startup -> "Startup"
  |`StepDown_from_Candidate -> "StepDown_from_Candidate"
  |`StepDown_from_Leader -> "StepDown_from_Leader"
  |`WinElecton -> "WinElecton"

